[project]
name = "dungeon-draw"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chuck", email = "charles.forsyth@ucr.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
]

[project.scripts]
dungeon-draw = "dungeon_draw:main"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]
